<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-ibr_pilots-mult']['en-us'] = "Inbound Route Pilots";
$text['title-ibr_pilots-mult']['ar-eg'] = "";
$text['title-ibr_pilots-mult']['de-at'] = ""; //copied from de-de
$text['title-ibr_pilots-mult']['de-ch'] = ""; //copied from de-de
$text['title-ibr_pilots-mult']['de-de'] = "";
$text['title-ibr_pilots-mult']['es-cl'] = "";
$text['title-ibr_pilots-mult']['es-mx'] = "";
$text['title-ibr_pilots-mult']['fr-ca'] = "";
$text['title-ibr_pilots-mult']['fr-fr'] = "";
$text['title-ibr_pilots-mult']['he-il'] = "";
$text['title-ibr_pilots-mult']['it-it'] = "";
$text['title-ibr_pilots-mult']['nl-nl'] = "";
$text['title-ibr_pilots-mult']['pl-pl'] = "";
$text['title-ibr_pilots-mult']['pt-br'] = "";
$text['title-ibr_pilots-mult']['pt-pt'] = "";
$text['title-ibr_pilots-mult']['ro-ro'] = "";
$text['title-ibr_pilots-mult']['ru-ru'] = "";
$text['title-ibr_pilots-mult']['sv-se'] = "";
$text['title-ibr_pilots-mult']['uk-ua'] = "";

$text['title-ibr_pilots']['en-us'] = "Inbound Route Pilot";
$text['title-ibr_pilots']['ar-eg'] = "";
$text['title-ibr_pilots']['de-at'] = ""; //copied from de-de
$text['title-ibr_pilots']['de-ch'] = ""; //copied from de-de
$text['title-ibr_pilots']['de-de'] = "";
$text['title-ibr_pilots']['es-cl'] = "";
$text['title-ibr_pilots']['es-mx'] = "";
$text['title-ibr_pilots']['fr-ca'] = "";
$text['title-ibr_pilots']['fr-fr'] = "";
$text['title-ibr_pilots']['he-il'] = "";
$text['title-ibr_pilots']['it-it'] = "";
$text['title-ibr_pilots']['nl-nl'] = "";
$text['title-ibr_pilots']['pl-pl'] = "";
$text['title-ibr_pilots']['pt-br'] = "";
$text['title-ibr_pilots']['pt-pt'] = "";
$text['title-ibr_pilots']['ro-ro'] = "";
$text['title-ibr_pilots']['ru-ru'] = "";
$text['title-ibr_pilots']['sv-se'] = "";
$text['title-ibr_pilots']['uk-ua'] = "";

$text['title_description-ibr_pilots']['en-us'] = "List of Inbound Route Pilots.";
$text['title_description-ibr_pilots']['ar-eg'] = "";
$text['title_description-ibr_pilots']['de-at'] = ""; //copied from de-de
$text['title_description-ibr_pilots']['de-ch'] = ""; //copied from de-de
$text['title_description-ibr_pilots']['de-de'] = "";
$text['title_description-ibr_pilots']['es-cl'] = "";
$text['title_description-ibr_pilots']['es-mx'] = "";
$text['title_description-ibr_pilots']['fr-ca'] = "";
$text['title_description-ibr_pilots']['fr-fr'] = "";
$text['title_description-ibr_pilots']['he-il'] = "";
$text['title_description-ibr_pilots']['it-it'] = "";
$text['title_description-ibr_pilots']['nl-nl'] = "";
$text['title_description-ibr_pilots']['pl-pl'] = "";
$text['title_description-ibr_pilots']['pt-br'] = "";
$text['title_description-ibr_pilots']['pt-pt'] = "";
$text['title_description-ibr_pilots']['ro-ro'] = "";
$text['title_description-ibr_pilots']['ru-ru'] = "";
$text['title_description-ibr_pilots']['sv-se'] = "";
$text['title_description-ibr_pilots']['uk-ua'] = "";

$text['label-ibr_pilots']['en-us'] = "Indound Route Pilot Number";
$text['label-ibr_pilots']['ar-eg'] = "";
$text['label-ibr_pilots']['de-at'] = ""; //copied from de-de
$text['label-ibr_pilots']['de-ch'] = ""; //copied from de-de
$text['label-ibr_pilots']['de-de'] = "";
$text['label-ibr_pilots']['es-cl'] = "";
$text['label-ibr_pilots']['es-mx'] = "";
$text['label-ibr_pilots']['fr-ca'] = "";
$text['label-ibr_pilots']['fr-fr'] = "";
$text['label-ibr_pilots']['he-il'] = "";
$text['label-ibr_pilots']['it-it'] = "";
$text['label-ibr_pilots']['nl-nl'] = "";
$text['label-ibr_pilots']['pl-pl'] = "";
$text['label-ibr_pilots']['pt-br'] = "";
$text['label-ibr_pilots']['pt-pt'] = "";
$text['label-ibr_pilots']['ro-ro'] = "";
$text['label-ibr_pilots']['ru-ru'] = "";
$text['label-ibr_pilots']['sv-se'] = "";
$text['label-ibr_pilots']['uk-ua'] = "";

$text['description-ibr_pilots']['en-us'] = "Enter the IBR Pilot Number. Format is 60-XX-YYYY for standard pilots, 61-XXXX-YY for account specific pilots.";
$text['description-ibr_pilots']['ar-eg'] = "";
$text['description-ibr_pilots']['de-at'] = ""; //copied from de-de
$text['description-ibr_pilots']['de-ch'] = ""; //copied from de-de
$text['description-ibr_pilots']['de-de'] = "";
$text['description-ibr_pilots']['es-cl'] = "";
$text['description-ibr_pilots']['es-mx'] = "";
$text['description-ibr_pilots']['fr-ca'] = "";
$text['description-ibr_pilots']['fr-fr'] = "";
$text['description-ibr_pilots']['he-il'] = "";
$text['description-ibr_pilots']['it-it'] = "";
$text['description-ibr_pilots']['nl-nl'] = "";
$text['description-ibr_pilots']['pl-pl'] = "";
$text['description-ibr_pilots']['pt-br'] = "";
$text['description-ibr_pilots']['pt-pt'] = "";
$text['description-ibr_pilots']['ro-ro'] = "";
$text['description-ibr_pilots']['ru-ru'] = "";
$text['description-ibr_pilots']['sv-se'] = "";
$text['description-ibr_pilots']['uk-ua'] = "";

$text['label-ibr_pilots_json']['en-us'] = "Indound Route Pilot JSON";
$text['label-ibr_pilots_json']['ar-eg'] = "";
$text['label-ibr_pilots_json']['de-at'] = ""; //copied from de-de
$text['label-ibr_pilots_json']['de-ch'] = ""; //copied from de-de
$text['label-ibr_pilots_json']['de-de'] = "";
$text['label-ibr_pilots_json']['es-cl'] = "";
$text['label-ibr_pilots_json']['es-mx'] = "";
$text['label-ibr_pilots_json']['fr-ca'] = "";
$text['label-ibr_pilots_json']['fr-fr'] = "";
$text['label-ibr_pilots_json']['he-il'] = "";
$text['label-ibr_pilots_json']['it-it'] = "";
$text['label-ibr_pilots_json']['nl-nl'] = "";
$text['label-ibr_pilots_json']['pl-pl'] = "";
$text['label-ibr_pilots_json']['pt-br'] = "";
$text['label-ibr_pilots_json']['pt-pt'] = "";
$text['label-ibr_pilots_json']['ro-ro'] = "";
$text['label-ibr_pilots_json']['ru-ru'] = "";
$text['label-ibr_pilots_json']['sv-se'] = "";
$text['label-ibr_pilots_json']['uk-ua'] = "";

$text['description-ibr_pilots_json']['en-us'] = "Enter the IBR Pilot JSON.";
$text['description-ibr_pilots_json']['ar-eg'] = "";
$text['description-ibr_pilots_json']['de-at'] = ""; //copied from de-de
$text['description-ibr_pilots_json']['de-ch'] = ""; //copied from de-de
$text['description-ibr_pilots_json']['de-de'] = "";
$text['description-ibr_pilots_json']['es-cl'] = "";
$text['description-ibr_pilots_json']['es-mx'] = "";
$text['description-ibr_pilots_json']['fr-ca'] = "";
$text['description-ibr_pilots_json']['fr-fr'] = "";
$text['description-ibr_pilots_json']['he-il'] = "";
$text['description-ibr_pilots_json']['it-it'] = "";
$text['description-ibr_pilots_json']['nl-nl'] = "";
$text['description-ibr_pilots_json']['pl-pl'] = "";
$text['description-ibr_pilots_json']['pt-br'] = "";
$text['description-ibr_pilots_json']['pt-pt'] = "";
$text['description-ibr_pilots_json']['ro-ro'] = "";
$text['description-ibr_pilots_json']['ru-ru'] = "";
$text['description-ibr_pilots_json']['sv-se'] = "";
$text['description-ibr_pilots_json']['uk-ua'] = "";

$text['label-enabled']['en-us'] = "Enabled";
$text['label-enabled']['ar-eg'] = "";
$text['label-enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-de'] = "Aktiviert";
$text['label-enabled']['es-cl'] = "";
$text['label-enabled']['es-mx'] = "";
$text['label-enabled']['fr-ca'] = "";
$text['label-enabled']['fr-fr'] = "";
$text['label-enabled']['he-il'] = "";
$text['label-enabled']['it-it'] = "Abilitato";
$text['label-enabled']['nl-nl'] = "";
$text['label-enabled']['pl-pl'] = "";
$text['label-enabled']['pt-br'] = "";
$text['label-enabled']['pt-pt'] = "";
$text['label-enabled']['ro-ro'] = "";
$text['label-enabled']['ru-ru'] = "Включено";
$text['label-enabled']['sv-se'] = "Aktiverad";
$text['label-enabled']['uk-ua'] = "";

$text['description-enabled']['en-us'] = "Enable or Disable the Inbound Route Pilot.";
$text['description-enabled']['ar-eg'] = "";
$text['description-enabled']['de-at'] = ""; //copied from de-de
$text['description-enabled']['de-ch'] = ""; //copied from de-de
$text['description-enabled']['de-de'] = "";
$text['description-enabled']['es-cl'] = "";
$text['description-enabled']['es-mx'] = "";
$text['description-enabled']['fr-ca'] = "";
$text['description-enabled']['fr-fr'] = "";
$text['description-enabled']['he-il'] = "";
$text['description-enabled']['it-it'] = "";
$text['description-enabled']['nl-nl'] = "";
$text['description-enabled']['pl-pl'] = "";
$text['description-enabled']['pt-br'] = "";
$text['description-enabled']['pt-pt'] = "";
$text['description-enabled']['ro-ro'] = "";
$text['description-enabled']['ru-ru'] = "";
$text['description-enabled']['sv-se'] = "";
$text['description-enabled']['uk-ua'] = "";

$text['label-description']['en-us'] = "Description";
$text['label-description']['ar-eg'] = "";
$text['label-description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-de'] = "Beschreibung";
$text['label-description']['es-cl'] = "";
$text['label-description']['es-mx'] = "";
$text['label-description']['fr-ca'] = "";
$text['label-description']['fr-fr'] = "";
$text['label-description']['he-il'] = "";
$text['label-description']['it-it'] = "Descrizione";
$text['label-description']['nl-nl'] = "";
$text['label-description']['pl-pl'] = "";
$text['label-description']['pt-br'] = "";
$text['label-description']['pt-pt'] = "";
$text['label-description']['ro-ro'] = "";
$text['label-description']['ru-ru'] = "Описание";
$text['label-description']['sv-se'] = "Beskrivning";
$text['label-description']['uk-ua'] = "";

$text['description-description']['en-us'] = "Enter the description.";
$text['description-description']['ar-eg'] = "";
$text['description-description']['de-at'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-ch'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-de'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['es-cl'] = "";
$text['description-description']['es-mx'] = "";
$text['description-description']['fr-ca'] = "";
$text['description-description']['fr-fr'] = "";
$text['description-description']['he-il'] = "";
$text['description-description']['it-it'] = "Inserire la descrizione.";
$text['description-description']['nl-nl'] = "";
$text['description-description']['pl-pl'] = "";
$text['description-description']['pt-br'] = "";
$text['description-description']['pt-pt'] = "";
$text['description-description']['ro-ro'] = "";
$text['description-description']['ru-ru'] = "Введите описание.";
$text['description-description']['sv-se'] = "Ange beskrivningen.";
$text['description-description']['uk-ua'] = "";

$text['label-column_name']['en-us'] = "Column Name";
$text['label-column_name']['ar-eg'] = "";
$text['label-column_name']['de-at'] = "";
$text['label-column_name']['de-ch'] = "";
$text['label-column_name']['de-de'] = "";
$text['label-column_name']['es-cl'] = "";
$text['label-column_name']['es-mx'] = "";
$text['label-column_name']['fr-ca'] = "";
$text['label-column_name']['fr-fr'] = "";
$text['label-column_name']['he-il'] = "";
$text['label-column_name']['it-it'] = "";
$text['label-column_name']['nl-nl'] = "";
$text['label-column_name']['pl-pl'] = "";
$text['label-column_name']['pt-br'] = "";
$text['label-column_name']['pt-pt'] = "";
$text['label-column_name']['ro-ro'] = "";
$text['label-column_name']['ru-ru'] = "";
$text['label-column_name']['sv-se'] = "";
$text['label-column_name']['uk-ua'] = "";

$text['button-add']['en-us'] = "Add";
$text['button-add']['ar-eg'] = "";
$text['button-add']['de-at'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-ch'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-de'] = "Hinzufügen";
$text['button-add']['es-cl'] = "";
$text['button-add']['es-mx'] = "";
$text['button-add']['fr-ca'] = "";
$text['button-add']['fr-fr'] = "";
$text['button-add']['he-il'] = "";
$text['button-add']['it-it'] = "Inserire";
$text['button-add']['nl-nl'] = "";
$text['button-add']['pl-pl'] = "";
$text['button-add']['pt-br'] = "";
$text['button-add']['pt-pt'] = "";
$text['button-add']['ro-ro'] = "";
$text['button-add']['ru-ru'] = "Добавить";
$text['button-add']['sv-se'] = "Lägg Till";
$text['button-add']['uk-ua'] = "";

$text['button-edit']['en-us'] = "Edit";
$text['button-edit']['ar-eg'] = "";
$text['button-edit']['de-at'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-ch'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-de'] = "Bearbeiten";
$text['button-edit']['es-cl'] = "";
$text['button-edit']['es-mx'] = "";
$text['button-edit']['fr-ca'] = "";
$text['button-edit']['fr-fr'] = "";
$text['button-edit']['he-il'] = "";
$text['button-edit']['it-it'] = "Modificare";
$text['button-edit']['nl-nl'] = "";
$text['button-edit']['pl-pl'] = "";
$text['button-edit']['pt-br'] = "";
$text['button-edit']['pt-pt'] = "";
$text['button-edit']['ro-ro'] = "";
$text['button-edit']['ru-ru'] = "Редактировать";
$text['button-edit']['sv-se'] = "Ändra";
$text['button-edit']['uk-ua'] = "";

$text['button-delete']['en-us'] = "Delete";
$text['button-delete']['ar-eg'] = "";
$text['button-delete']['de-at'] = "Löschen"; //copied from de-de
$text['button-delete']['de-ch'] = "Löschen"; //copied from de-de
$text['button-delete']['de-de'] = "Löschen";
$text['button-delete']['es-cl'] = "";
$text['button-delete']['es-mx'] = "";
$text['button-delete']['fr-ca'] = "";
$text['button-delete']['fr-fr'] = "";
$text['button-delete']['he-il'] = "";
$text['button-delete']['it-it'] = "Cancellare";
$text['button-delete']['nl-nl'] = "";
$text['button-delete']['pl-pl'] = "";
$text['button-delete']['pt-br'] = "";
$text['button-delete']['pt-pt'] = "";
$text['button-delete']['ro-ro'] = "";
$text['button-delete']['ru-ru'] = "Удалить";
$text['button-delete']['sv-se'] = "Ta Bort";
$text['button-delete']['uk-ua'] = "";

$text['button-save']['en-us'] = "Save";
$text['button-save']['ar-eg'] = "";
$text['button-save']['de-at'] = "Speichern"; //copied from de-de
$text['button-save']['de-ch'] = "Speichern"; //copied from de-de
$text['button-save']['de-de'] = "Speichern";
$text['button-save']['es-cl'] = "";
$text['button-save']['es-mx'] = "";
$text['button-save']['fr-ca'] = "";
$text['button-save']['fr-fr'] = "";
$text['button-save']['he-il'] = "";
$text['button-save']['it-it'] = "Salva";
$text['button-save']['nl-nl'] = "";
$text['button-save']['pl-pl'] = "";
$text['button-save']['pt-br'] = "Guardar"; //copied from pt-pt
$text['button-save']['pt-pt'] = "Guardar";
$text['button-save']['ro-ro'] = "";
$text['button-save']['ru-ru'] = "Сохранить";
$text['button-save']['sv-se'] = "Spara";
$text['button-save']['uk-ua'] = "";

$text['button-view']['en-us'] = "View";
$text['button-view']['ar-eg'] = "";
$text['button-view']['de-at'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-ch'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-de'] = "Anzeigen";
$text['button-view']['es-cl'] = "";
$text['button-view']['es-mx'] = "";
$text['button-view']['fr-ca'] = "";
$text['button-view']['fr-fr'] = "";
$text['button-view']['he-il'] = "";
$text['button-view']['it-it'] = "Mostra";
$text['button-view']['nl-nl'] = "";
$text['button-view']['pl-pl'] = "";
$text['button-view']['pt-br'] = "";
$text['button-view']['pt-pt'] = "";
$text['button-view']['ro-ro'] = "";
$text['button-view']['ru-ru'] = "";
$text['button-view']['sv-se'] = "Visa";
$text['button-view']['uk-ua'] = "";

$text['button-back']['en-us'] = "Back";
$text['button-back']['ar-eg'] = "";
$text['button-back']['de-at'] = "Zurück"; //copied from de-de
$text['button-back']['de-ch'] = "Zurück"; //copied from de-de
$text['button-back']['de-de'] = "Zurück";
$text['button-back']['es-cl'] = "";
$text['button-back']['es-mx'] = "";
$text['button-back']['fr-ca'] = "";
$text['button-back']['fr-fr'] = "";
$text['button-back']['he-il'] = "";
$text['button-back']['it-it'] = "Indietro";
$text['button-back']['nl-nl'] = "";
$text['button-back']['pl-pl'] = "";
$text['button-back']['pt-br'] = "Voltar"; //copied from pt-pt
$text['button-back']['pt-pt'] = "Voltar";
$text['button-back']['ro-ro'] = "";
$text['button-back']['ru-ru'] = "Назад";
$text['button-back']['sv-se'] = "Tillbaka";
$text['button-back']['uk-ua'] = "";

$text['confirm-delete']['en-us'] = "Do you really want to delete this?";
$text['confirm-delete']['ar-eg'] = "";
$text['confirm-delete']['de-at'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-ch'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-de'] = "Möchten Sie dieses wirklich löschen?";
$text['confirm-delete']['es-cl'] = "";
$text['confirm-delete']['es-mx'] = "";
$text['confirm-delete']['fr-ca'] = "";
$text['confirm-delete']['fr-fr'] = "";
$text['confirm-delete']['he-il'] = "";
$text['confirm-delete']['it-it'] = "Vuoi veramente cancellarlo?";
$text['confirm-delete']['nl-nl'] = "";
$text['confirm-delete']['pl-pl'] = "";
$text['confirm-delete']['pt-br'] = "";
$text['confirm-delete']['pt-pt'] = "";
$text['confirm-delete']['ro-ro'] = "";
$text['confirm-delete']['ru-ru'] = "Вы действительно хотите удалить это?";
$text['confirm-delete']['sv-se'] = "Vill du verkligen ta bort detta?";
$text['confirm-delete']['uk-ua'] = "";

$text['message-add']['en-us'] = "Add Completed";
$text['message-add']['ar-eg'] = "";
$text['message-add']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-de'] = "Erfolgreich hinzugefügt";
$text['message-add']['es-cl'] = "";
$text['message-add']['es-mx'] = "";
$text['message-add']['fr-ca'] = "";
$text['message-add']['fr-fr'] = "";
$text['message-add']['he-il'] = "";
$text['message-add']['it-it'] = "Inserimento Completato";
$text['message-add']['nl-nl'] = "";
$text['message-add']['pl-pl'] = "";
$text['message-add']['pt-br'] = "";
$text['message-add']['pt-pt'] = "";
$text['message-add']['ro-ro'] = "";
$text['message-add']['ru-ru'] = "Добавление выполнено";
$text['message-add']['sv-se'] = "Tillagd";
$text['message-add']['uk-ua'] = "";

$text['message-update']['en-us'] = "Update Completed";
$text['message-update']['ar-eg'] = "";
$text['message-update']['de-at'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-ch'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-de'] = "Aktualisierung durchgeführt";
$text['message-update']['es-cl'] = "";
$text['message-update']['es-mx'] = "";
$text['message-update']['fr-ca'] = "";
$text['message-update']['fr-fr'] = "";
$text['message-update']['he-il'] = "";
$text['message-update']['it-it'] = "Aggiornamento Completato";
$text['message-update']['nl-nl'] = "";
$text['message-update']['pl-pl'] = "";
$text['message-update']['pt-br'] = "";
$text['message-update']['pt-pt'] = "";
$text['message-update']['ro-ro'] = "";
$text['message-update']['ru-ru'] = "Обновление завершено";
$text['message-update']['sv-se'] = "Ändring Utförd";
$text['message-update']['uk-ua'] = "";

$text['message-delete']['en-us'] = "Delete Completed";
$text['message-delete']['ar-eg'] = "";
$text['message-delete']['de-at'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-ch'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-de'] = "Erfolgreich gelöscht";
$text['message-delete']['es-cl'] = "";
$text['message-delete']['es-mx'] = "";
$text['message-delete']['fr-ca'] = "";
$text['message-delete']['fr-fr'] = "";
$text['message-delete']['he-il'] = "";
$text['message-delete']['it-it'] = "Cancellazione Completato";
$text['message-delete']['nl-nl'] = "";
$text['message-delete']['pl-pl'] = "";
$text['message-delete']['pt-br'] = "";
$text['message-delete']['pt-pt'] = "";
$text['message-delete']['ro-ro'] = "";
$text['message-delete']['ru-ru'] = "Удаление завершено";
$text['message-delete']['sv-se'] = "Borttagen";
$text['message-delete']['uk-ua'] = "";

$text['message-required']['en-us'] = "Please provide: ";
$text['message-required']['ar-eg'] = "";
$text['message-required']['de-at'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-ch'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-de'] = "Bitte geben Sie folgendes an:";
$text['message-required']['es-cl'] = "";
$text['message-required']['es-mx'] = "";
$text['message-required']['fr-ca'] = "";
$text['message-required']['fr-fr'] = "";
$text['message-required']['he-il'] = "";
$text['message-required']['it-it'] = "Prego fornire:";
$text['message-required']['nl-nl'] = "";
$text['message-required']['pl-pl'] = "";
$text['message-required']['pt-br'] = "";
$text['message-required']['pt-pt'] = "";
$text['message-required']['ro-ro'] = "";
$text['message-required']['ru-ru'] = "Пожалуйста предоставьте: ";
$text['message-required']['sv-se'] = "Var god ange: ";
$text['message-required']['uk-ua'] = "";

?>
